### ISSUE TITLE
qt5-default requirement in readme.md deprecated in Ubuntu 21.04

### ISSUE THREAD

**Issue by knasiotis** [ENSTABretagneRobotics/VIBES#119]
I found a simple workaround [here](https://stackoverflow.com/questions/67373586/install-qt5-on-ubuntu-21-04)
`sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`

I believe README.MD can be easily updated.

**Comment by lebarsfa** [comment]
Thank you, it has been more or less taken into account in the recent commits...
