### ISSUE TITLE
Draw a submarine robot

### ISSUE THREAD

**Issue by nicolaje** [ENSTABretagneRobotics/VIBES#15]
Include a graphics on the viewer side that represents a 2D submarine, defined by its state vector (x,y,theta,scale) where scale is the length on its local X axis

**Comment by SimonRohou** [comment]
Done. 30c9d2f48cd467b5b34908934a90e86c2015c8f2

```
vibes::drawAUV(0, 0, 50, 5, "blue[yellow]")
```

**Comment by dvinc** [comment]
Closed 30c9d2f48cd467b5b34908934a90e86c2015c8f2. Thanks Simon!
