### ISSUE TITLE
On OSX, math functions aren't found by the default toolchain

### ISSUE THREAD

**Issue by nicolaje** [ENSTABretagneRobotics/VIBES#77]
Building the viewer yields:

vibesgraphicsitem.cpp:1288:34: error: no member named 'cos' in namespace
      'std'; did you mean simply 'cos'?
        double m1_x = cx + rho_m*std::cos(-theta_m*M_PI/180.0);

Seems to be due to a missing #include <cmath>

**Comment by benEnsta** [comment]
directive #include <cmath> is missing in vibesgraphicsitem.cpp

**Comment by nicolaje** [comment]
Yup, I ´ll patch that tonight.
